version: '3.7'
services:
  nginx:
    build:
      context: ./hako/nginx
      dockerfile: Dockerfile
    ports:
      - 80:80
      - 443:443
    depends_on:
      - app
  app:
    build: .
    command: bundle exec rackup config.ru -p 4567
    tty: true
    stdin_open: true
