source 'https://rubygems.org'

gem 'aws-sdk-cloudfront'
gem 'aws-sdk-s3'
gem 'haml', '~> 5.0'
gem 'html-pipeline'
gem 'metainspector'
gem 'middleman', '~> 4.2'
gem 'mime-types'
gem 'mini_exiftool'
gem 'mini_magick'
gem 'pry'
gem 'redcarpet'
gem 'rubocop'
